#!/bin/bash
#Lars Web Tools

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${SCRIPT_PATH}/lib/core.sh"
source "${SCRIPT_PATH}/lib/apache.sh"

if [ "$(whoami)" = "root" ]; then
	abort "This program should not be run as root."
fi

if [ "$#" -lt 1 ]; then
	abort "Usage: `basename $0` COMMAND [...]"
fi

LWT_COMMAND="$1"
shift

case "$LWT_COMMAND" in
	"create")	source "$SCRIPT_PATH/lwt-create" $@
				;;

	"delete")	source "$SCRIPT_PATH/lwt-delete" $@
				;;

	# "backup")	source "$SCRIPT_PATH/lwt-backup" $2
	# 			;;

	# "rename")	source "$SCRIPT_PATH/lwt-rename" $2 $3
	# 			;;

	# "enable")	source "$SCRIPT_PATH/lwt-enable" $2
	# 			;;

	# "disable")	source "$SCRIPT_PATH/lwt-disable" $2
	# 			;;

	# "default")  source "$SCRIPT_PATH/lwt-default" $2
	#             ;;

	*) 			echo "No such command."
				;;
esac
