#!/bin/bash
# Create - Lars Web Tools

readonly TLD=".localhost"

abort() {
	echo ${BASH_SOURCE[1]##*/}[${BASH_LINENO[0]}]: "${@}"
	echo "Aborting."
	exit 1
}

# vercomp by Dennis Williamson, see http://stackoverflow.com/a/4025065/1227116
vercomp() {
	if [[ $1 == $2 ]]
	then
		return 0
	fi
	local IFS=.
	local i ver1=($1) ver2=($2)
	# fill empty fields in ver1 with zeros
	for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
	do
		ver1[i]=0
	done
	for ((i=0; i<${#ver1[@]}; i++))
	do
		if [[ -z ${ver2[i]} ]]
		then
			# fill empty fields in ver2 with zeros
			ver2[i]=0
		fi
		if ((10#${ver1[i]} > 10#${ver2[i]}))
		then
			return 1
		fi
		if ((10#${ver1[i]} < 10#${ver2[i]}))
		then
			return 2
		fi
	done
	return 0
}

apache::version() {
	apachectl -v &> /dev/null
	if [ $? -ne 0 ]; then
		abort "Error running \`apachectl -v\`."
	fi

	local apache_ver="`apachectl -v 2> /dev/null`"
	apache_ver=`echo "$apache_ver" | grep "Server version"`
	apache_ver=`expr "$apache_ver" : 'Server version: Apache/\(.*\) .*'`
	echo $apache_ver
}

apache::config_get() {
	if [ "$#" -ne 1 ]; then abort "Not enough parameters."; fi

	local __key=$1

	apachectl -t -D DUMP_RUN_CFG &> /dev/null
	if [ $? -ne 0 ]; then
		abort "Error running \`apachectl -t -D DUMP_RUN_CFG\`."
	fi

	local conf="`apachectl -S 2> /dev/null`"
	conf=`echo "$conf" | grep "${__key}"`
	conf=`expr "$conf" : "${__key}: \"\(.*\)\""`

	echo "$conf"
}

vercomp "`apache::version`" "2.4.0"
if [ $? -ne 1 ]; then
	abort "Apache 2.4.0 or later required."
fi

if [ "$#" -ne 1 ]; then
	abort "Usage: $0 PROJECT"
fi

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APACHE_DIR="`apache::config_get "ServerRoot"`"
PROJECT=$1
PROJECT_DIR="`pwd`/${PROJECT}"
DOMAIN="${PROJECT}${TLD}"
VHOST="${APACHE_DIR}/sites-available/${DOMAIN}.conf"
VHOST_CONFIG=$(source ${SCRIPT_PATH}/lwt_vhost_conf)

if [ ! -d "${APACHE_DIR}/sites-available" ]; then
	abort "Could not find apache's site configuration directory."
fi

if [ -d "$PROJECT" ]; then
	abort "The directory [$PROJECT] already exists."
fi

if [ -f "$VHOST" -o -h "$VHOST" ]; then
	abort "The virtual host file [$VHOST] already exists."
fi

grep -q "$DOMAIN" /etc/hosts
if [ $? -eq 0 ]; then
	echo "The domain [$DOMAIN] is already present in [/etc/hosts]. This script will not add it again."
	echo "Do you wish to continue? (y/n)"
	read REPLY
	if [[ ! $REPLY =~ ^[Yy]$ ]]; then
		abort
		exit 1
	fi
fi

# Get sudo permissions
echo "We need root permissions to add the virtual host."
sudo echo -n ""
if [ $? -eq 1 ]; then
	abort "Permission denied"
fi

# Create folders and copy default files
echo -n "Creating web directory with default folder structure in [$PROJECT_DIR]... "
mkdir "$PROJECT_DIR"

mkdir "${PROJECT_DIR}/public"
mkdir "${PROJECT_DIR}/data"
mkdir "${PROJECT_DIR}/data/logs"
echo "done!"

# Create Virtual Host
echo -n "Creating Virtual Host for [$DOMAIN]... "
mkdir "${PROJECT_DIR}/data/vhost"
echo "$VHOST_CONFIG" > "${PROJECT_DIR}/data/vhost/vhost.apache2"
sudo ln -s "${PROJECT_DIR}/data/vhost/vhost.apache2" "$VHOST"
echo "done!"

# Enable Virtual Host
echo -n "Enabling Virtual Host for [$DOMAIN]... "
sudo sh -c "a2ensite \"$DOMAIN\" > /dev/null"
echo "done!"

# Add entry in /etc/hosts
echo -n "Adding entry in /etc/hosts... "
grep -q "$DOMAIN" "/etc/hosts"
if [ ! $? -eq 0 ]; then
	sudo sh -c "echo \"127.0.0.1\t$DOMAIN\" >> \"/etc/hosts\""
	echo "done!"
else
	echo "NOT done! Host is already present in [/etc/hosts]."
fi

echo
echo "Reload apache for changes to take effect."
echo

exit 0
