#!/bin/bash
# Create - Lars Web Tools

if [ "$#" -ne 1 ]; then
	abort "Usage: $0 PROJECT"
fi

readonly TLD=".localhost"
PROJECT=$1
PROJECT_DIR="`pwd`/${PROJECT}"
DOMAIN="${PROJECT}${TLD}"

apache::init

if [ -d "$PROJECT" ]; then
	abort "The directory [$PROJECT] already exists."
fi

apache::host_exists "$DOMAIN"
if [ $? -eq 0 ]; then
	abort "The virtual host for [$DOMAIN] already exists."
fi

grep -q "$DOMAIN" /etc/hosts
if [ $? -eq 0 ]; then
	confirm_or_exit "The domain [$DOMAIN] is already present in [/etc/hosts]. This script will not add it again."
fi

# Get sudo permissions
sudo_please "We need root permissions to add the virtual host."

# Create folders and copy default files
echo -n "Creating web directory with default folder structure in [$PROJECT_DIR]... "
mkdir "$PROJECT_DIR"

mkdir "${PROJECT_DIR}/public"
mkdir "${PROJECT_DIR}/data"
mkdir "${PROJECT_DIR}/data/logs"

echo "Welcome to project ${PROJECT}!" >> "${PROJECT_DIR}/public/index.html"

echo "done!"

# Create Virtual Host
echo -n "Creating Virtual Host for [$DOMAIN]... "
mkdir "${PROJECT_DIR}/data/vhost"
apache::host_create "$DOMAIN" "${PROJECT_DIR}/data/vhost/vhost.apache2"
echo "done!"

# Enable Virtual Host
echo -n "Enabling Virtual Host for [$DOMAIN]... "
apache::host_enable "$DOMAIN"
echo "done!"

# Add entry in /etc/hosts
echo -n "Adding entry in /etc/hosts... "
grep -q "$DOMAIN" "/etc/hosts"
if [ ! $? -eq 0 ]; then
	sudo sh -c "echo \"127.0.0.1\t$DOMAIN\" >> \"/etc/hosts\""
	echo "done!"
else
	echo "Host is already present in [/etc/hosts]."
fi

echo
echo "Reload apache for changes to take effect."
echo

exit 0
