#!/bin/bash
# Delete - Lars Web Tools

# This check is not really necessary.
#if [ ! -d $WEB_DIR -o ! -f $VIRTUAL_HOST_FILE ]; then
#	echo "The directory [$WEB_DIR] or the virtual host file [$VIRTUAL_HOST_FILE] doesn't exist."
#	echo "Aborting."
#	exit 1
#fi

echo "Do you wish to DELETE [$LOCAL_DOMAIN] and ALL CONTENT in [$WEB_DIR]? This action can not be undone."
echo "Continue? (y/n)"
read REPLY 
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	exit 1
fi

echo -n "Deleting folder [$WEB_DIR] and all content... "
rm -r "$WEB_DIR"
echo "done!"

echo -n "Disabling the Virtual Host for [$LOCAL_DOMAIN]... "
sudo sh -c "a2dissite \"$LOCAL_DOMAIN\" > /dev/null"
echo "done!"

echo -n "Removing up the Virtual Host for [$LOCAL_DOMAIN]... "
sudo rm "$VIRTUAL_HOST_FILE"
echo "done!"

echo -n "Removing entry from [$ETC_HOSTS_FILE]... "
grep -q "$LOCAL_DOMAIN" "$ETC_HOSTS_FILE"
if [ $? -eq $GREP_SUCCESS ]
then
	TEMP_FILE="/tmp/zf_delete_project_tmp"
	sed "/$LOCAL_IP\t$LOCAL_DOMAIN/d" $ETC_HOSTS_FILE > $TEMP_FILE
	sudo mv "$TEMP_FILE" "$ETC_HOSTS_FILE"
	echo "done!"
else
	echo "aborted. Host is not present in [$ETC_HOSTS_FILE]."
fi

echo 
echo "Restart apache for changes to take effect."
echo 
