#!/bin/bash
# Delete - Lars Web Tools

readonly TLD=".localhost"
PROJECT=$1
PROJECT_DIR="`pwd`/${PROJECT}"
DOMAIN="${PROJECT}${TLD}"

apache::init

if [ ! -d $PROJECT_DIR ]; then
	abort "The directory [$PROJECT_DIR] doesn't exist."
fi

apache::host_exists "$DOMAIN"
if [ $? -ne 0 ]; then
	abort "The virtual host file [$VIRTUAL_HOST_FILE] doesn't exist."
fi

confirm_or_exit "Do you wish to DELETE [$DOMAIN] and ALL CONTENT in [$PROJECT_DIR]? This action can not be undone."

# Get sudo permissions
sudo_please "We need root permissions to remove the virtual host."

echo -n "Deleting folder [$PROJECT_DIR] and all content... "
sudo rm -r "$PROJECT_DIR"
echo "done!"

echo -n "Disabling the Virtual Host for [$DOMAIN]... "
apache::host_disable "$DOMAIN"
echo "done!"

echo -n "Removing up the Virtual Host for [$DOMAIN]... "
apache::host_delete "$DOMAIN"
echo "done!"

echo -n "Removing entry from [/etc/hosts]... "
grep -q "$DOMAIN" "/etc/hosts"
if [ $? -eq 0 ]
then
	TEMP_FILE="/tmp/lwt_delete_project_tmp"
	sed "/127.0.0.1\t$DOMAIN/d" /etc/hosts > $TEMP_FILE
	sudo mv "$TEMP_FILE" "/etc/hosts"
	echo "done!"
else
	echo "Host is not present in [/etc/hosts]."
fi

echo
echo "Reload apache for changes to take effect."
echo

exit 0
